# a.Using Numpy, write a basic array of operations on single array to add x to each element of array and subtract y from each element of array.

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a+3)
print(a-6)

[4 5 6]
[-5 -4 -3]


# b. Using Numpy, write a program to add, subtract and multiply two matrices. 

In [4]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[4,5,6],[7,8,9],[10,11,12]])
print('sum:',c+b)
print('difference:',c-b)
print('product:',np.dot(b,c))

sum: [[ 5  7  9]
 [11 13 15]
 [17 19 21]]
difference: [[3 3 3]
 [3 3 3]
 [3 3 3]]
product: [[ 48  54  60]
 [111 126 141]
 [174 198 222]]


# c.Write a Python program to do the following operations: Library: NumPy


# i)	Create multi-dimensional arrays and find its shape and dimension 

In [8]:
m=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print('shape:',m.shape)
print('dimensions:',m.ndim)


shape: (2, 2, 3)
dimensions: 3


# ii)	Create a matrix full of zeros and ones 

In [9]:
zeros=np.zeros([2,2])
ones=np.ones([3,3])
print(ones)
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


# iii)	Reshape and flatten data in the array 

In [13]:
resh=a.reshape([3,1])
print(resh)
f=zeros.flatten()
print(f)

[[1]
 [2]
 [3]]
[0. 0. 0. 0.]


# iv)	Append data vertically and horizontally 

In [19]:
b=np.array([4,5,6])
horizontal_append=np.hstack((a,b))
print(horizontal_append)
vertical_append=np.vstack((a,b))
print(vertical_append)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# v)	Apply indexing and slicing on array 

In [21]:
d=b[1:]
print(d)
c=b[0]
print(c)

[5 6]
4


# vi)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [28]:
import statistics as s
print(a.min())
print(a.max())
print(a.mean())
print(s.median(a))
print(np.std(a))

1
3
2.0
2
0.816496580927726


# vii)	Dot and matrix product of two arrays 

In [38]:
print('dot:',a*b)
b=b.reshape(1,3)
print('matrix multiplication:',np.dot(a,(b.T)))

dot: [[ 4 10 18]]
matrix multiplication: [32]


# viii)	Compute the Eigen values of a matrix 

In [40]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.eigvals(e))

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


# ix)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [41]:
coef=np.array([[3,1],[1,2]])
con=np.array([9,8])
np.linalg.solve(coef,con)

array([2., 3.])

# x)	Compute the multiplicative inverse of a matrix 

In [44]:
b=np.array([[1,2,3],[4,5,6],[7,8,10]])
inv=np.linalg.inv(b)
print(inv)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


# xi)	Compute the rank of a matrix 

In [47]:
rank=np.linalg.matrix_rank([[1,2,3],[2,1,4],[3,0,5]])
print(rank)

2


# xii)	 Compute the determinant of an array

In [53]:
de=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(de.shape)
det1=np.linalg.det(de)
print(det1)

(3, 3)
-9.51619735392994e-16
