In [76]:
import numpy as np

In [77]:
wines=np.genfromtxt('Z:/y20cs190_saleembasha/3 rd year/sem 5/CS 352 DA lab/winequality-red.csv',delimiter=';',skip_header=1)

In [78]:
wines.dtype='float'

In [79]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [80]:
wines.shape

(1599, 12)

In [81]:
wines[(2,3)]

2.3

In [82]:
for i in range(0,3):
    print(i+1,'element in fourth column is:',wines[(i,3)])

1 element in fourth column is: 1.9
2 element in fourth column is: 2.6
3 element in fourth column is: 2.3


In [83]:
wines[:3,[3]]

array([[1.9],
       [2.6],
       [2.3]])

In [84]:
wines[0:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [85]:
wines[3]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [86]:
print('value of 2nd row and 6th column element before Assign value 10 to it is:')
print(wines[1,5])
wines[1,5]=10
print('value of 2nd row and 6th column element after Assign value 10 to it is:')
print(wines[1,5])

value of 2nd row and 6th column element before Assign value 10 to it is:
25.0
value of 2nd row and 6th column element after Assign value 10 to it is:
10.0


In [87]:
slice_new=wines[0:,9]
print('slice_new array before assigning 666 to all elements of slice_new:')
print(slice_new)
slice_new[0:]=666
print('slice_new array after assigning 666 to all elements of slice_new:')
print(slice_new)

slice_new array before assigning 666 to all elements of slice_new:
[0.56 0.68 0.65 ... 0.75 0.71 0.66]
slice_new array after assigning 666 to all elements of slice_new:
[666. 666. 666. ... 666. 666. 666.]


In [88]:
wines

array([[7.40e+00, 7.00e-01, 0.00e+00, ..., 6.66e+02, 9.40e+00, 5.00e+00],
       [7.80e+00, 8.80e-01, 0.00e+00, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       [7.80e+00, 7.60e-01, 4.00e-02, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       ...,
       [6.30e+00, 5.10e-01, 1.30e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00],
       [5.90e+00, 6.45e-01, 1.20e-01, ..., 6.66e+02, 1.02e+01, 5.00e+00],
       [6.00e+00, 3.10e-01, 4.70e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00]])

In [89]:
print('data type of wines array before changing to int  is:',wines.dtype)
wines=wines.astype(np.int64)
print('data type of wines array  after changing to int is:',wines.dtype)

data type of wines array before changing to int  is: float64
data type of wines array  after changing to int is: int64


In [91]:
wines

array([[  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       ...,
       [  6,   0,   0, ..., 666,  11,   6],
       [  5,   0,   0, ..., 666,  10,   5],
       [  6,   0,   0, ..., 666,  11,   6]], dtype=int64)

In [90]:
print('quality scores wines before Adding 10 points to each is:',wines[:,11])
print('quality scores wines after Adding 10 points to each is:',wines[:,11]+10)

quality scores wines before Adding 10 points to each is: [5 5 5 ... 6 5 6]
quality scores wines after Adding 10 points to each is: [15 15 15 ... 16 15 16]


In [92]:
wines

array([[  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       ...,
       [  6,   0,   0, ..., 666,  11,   6],
       [  5,   0,   0, ..., 666,  10,   5],
       [  6,   0,   0, ..., 666,  11,   6]], dtype=int64)

In [93]:
np.sum(wines)

1210398

In [94]:
np.sum(wines,axis=0)

array([  12589,      24,       1,    3350,       0,   25367,   74301,
            81,    4770, 1064934,   15969,    9012], dtype=int64)

In [95]:
np.sum(wines,axis=1)

array([736, 769, 761, ..., 763, 767, 755], dtype=int64)

In [96]:
np.cumsum(wines[0:,11])

array([   5,   10,   15, ..., 9001, 9006, 9012], dtype=int64)

In [97]:
np.sum(wines[0:,11])

9012

In [98]:
print(wines[0:,10])
print(wines[0:,11])

[ 9  9  9 ... 11 10 11]
[5 5 5 ... 6 5 6]


In [99]:
wines[0:,10]*wines[0:,11]

array([45, 45, 45, ..., 66, 50, 66], dtype=int64)

In [120]:
c=0
for i in wines[:,11]:
    if i>5:
        print(i,end=' ')
        c+=1

6 7 7 7 6 6 6 6 6 6 6 6 7 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 6 7 7 7 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 7 7 6 6 6 6 6 6 7 7 8 6 6 6 6 6 6 6 8 7 6 7 7 6 6 7 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 7 6 6 6 7 6 6 6 6 7 7 6 6 7 6 6 6 6 6 7 6 6 6 6 6 6 6 7 7 6 6 7 6 7 7 6 6 6 7 6 7 6 6 6 6 6 6 6 6 6 6 7 8 6 7 6 6 6 6 6 6 6 7 6 6 7 6 6 7 7 7 7 6 6 6 7 6 6 6 6 6 8 6 7 7 7 6 6 6 6 6 6 7 8 7 6 6 6 6 6 6 6 6 6 6 8 6 6 7 6 6 7 7 6 6 8 6 8 6 6 7 7 7 7 7 7 6 6 7 6 6 7 7 6 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 6 7 8 7 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 7 6 7 7 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 6 7 6 6 7 7 7 6 6 6 6 6 7 7 8 6 6 7 7 7 7 6 6 6 6 6 7 6 7 7 6 6 6 6 6 6 6 7 7 7 6 6 6 6 6 6 7 6 6 6 6 7 6 7 7 7 7 7 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 7 6 7 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 6 6 6 7 6 6 6 6 7 6 6 6 7 7 7 6 6 6 6 7 6 6 6 7 7 6 6 7 7 7 7 7 

In [118]:
b=np.where(wines[:,11]>5)
wines[b,11]

array([[6, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 7, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 7, 7, 7, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 6, 6, 6,
        6, 6, 7, 7, 8, 6, 6, 6, 6, 6, 6, 6, 8, 7, 6, 7, 7, 6, 6, 7, 7, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 7, 6, 6, 6, 7, 6, 6,
        6, 6, 7, 7, 6, 6, 7, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 7, 7,
        6, 6, 7, 6, 7, 7, 6, 6, 6, 7, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        7, 8, 6, 7, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 7, 6, 6, 7, 7, 7, 7, 6,
        6, 6, 7, 6, 6, 6, 6, 6, 8, 6, 7, 7, 7, 6, 6, 6, 6, 6, 6, 7, 8, 7,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 7, 6, 6, 7, 7, 6, 6, 8, 6,
        8, 6, 6, 7, 7, 7, 7, 7, 7, 6, 6, 7, 6, 6, 7, 7, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 

In [126]:
a=np.where(wines[:,11]==10)
if wines[a,11].size>0:
    print('wines have a quality rating equal to 10')
else:
    print('no wines have a quality rating equal to 10')

no wines have a quality rating equal to 10


In [134]:
print(wines[wines[:,-1]>7])

[[  7   0   0   3   0  15  37   0   3 666  12   8]
 [ 10   0   0   6   0   5  13   0   3 666  12   8]
 [  5   0   0   1   0  12  88   0   3 666  12   8]
 [ 12   0   0   2   0   6  29   0   2 666   9   8]
 [ 11   0   0   5   0   6  19   0   3 666  13   8]
 [  9   0   0   2   0   6  17   0   3 666  11   8]
 [ 10   0   0   2   0   5  16   0   3 666  11   8]
 [ 10   0   0   2   0   5  16   0   3 666  11   8]
 [  5   0   0   2   0  19  50   0   3 666  14   8]
 [  7   0   0   2   0  34  45   0   3 666  12   8]
 [  9   0   0   1   0   7  16   0   3 666  12   8]
 [ 10   0   0   1   0  42  74   0   2 666  11   8]
 [  7   0   0   2   0   8  17   0   3 666  13   8]
 [  8   0   0   1   0   6  12   0   3 666  11   8]
 [  5   0   0   1   0  28  87   0   3 666  14   8]
 [  7   0   0   1   0   3  13   0   3 666  10   8]
 [  7   0   0   2   0  15  29   0   3 666  11   8]
 [  7   0   0   1   0  17  24   0   3 666  11   8]]


In [138]:
print(wines[(wines[:,-1]>7) & (wines[:,-2]>10)])

[[  7   0   0   3   0  15  37   0   3 666  12   8]
 [ 10   0   0   6   0   5  13   0   3 666  12   8]
 [  5   0   0   1   0  12  88   0   3 666  12   8]
 [ 11   0   0   5   0   6  19   0   3 666  13   8]
 [  9   0   0   2   0   6  17   0   3 666  11   8]
 [ 10   0   0   2   0   5  16   0   3 666  11   8]
 [ 10   0   0   2   0   5  16   0   3 666  11   8]
 [  5   0   0   2   0  19  50   0   3 666  14   8]
 [  7   0   0   2   0  34  45   0   3 666  12   8]
 [  9   0   0   1   0   7  16   0   3 666  12   8]
 [ 10   0   0   1   0  42  74   0   2 666  11   8]
 [  7   0   0   2   0   8  17   0   3 666  13   8]
 [  8   0   0   1   0   6  12   0   3 666  11   8]
 [  5   0   0   1   0  28  87   0   3 666  14   8]
 [  7   0   0   2   0  15  29   0   3 666  11   8]
 [  7   0   0   1   0  17  24   0   3 666  11   8]]


In [129]:
np.reshape(wines,(12,1599))

array([[  7,   0,   0, ...,   6,   0,   0],
       [  1,   0,  17, ...,   3,   0,  26],
       [ 61,   1,   3, ...,  42,   0,   3],
       ...,
       [  2,   0,  23, ...,   1,   0,   6],
       [ 25,   0,   3, ...,  53,   0,   3],
       [666,   9,   5, ..., 666,  11,   6]], dtype=int64)