In [5]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [10]:
l=[1,2,3]
a=np.array(l)
if 0 in a:
    print('zero present in given numpy array')
else:
    print('no zero is there in the given numpy array')

no zero is there in the given numpy array


In [23]:
l=[0]*10
l.extend([1]*10)
l.extend([5]*10)
b=np.array(l)
print(b)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


In [25]:
li=[]
for i in range(30,71,2):
    li.append(i)
even=np.array(li)
print(even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [26]:
print(np.array([1]*9).reshape(3,3))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [32]:
test=[[1 ,1],
 [1 ,1 ],
 [1, 1]]
print('no of rows:',len(np.array(test)))
print('no of columns:',len(np.array(test)[0]))

no of rows: 3
no of columns: 2


In [40]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [49]:
sumarr=np.array([[1,2,3],[4,5,6],[7,8,9]]).reshape(3,3)
print('sum of 1st row:',sum(sumarr[0]),'\nsum of 2nd row:',sum(sumarr[1]),'\nsum of 3rd row:',sum(sumarr[2]))
print('sum of 1st column:',sum(sumarr)[0],'\nsum of 2nd row:',sum(sumarr)[1],'\nsum of 3rd row:',sum(sumarr)[2])
print('sum of given arrayis :',sum(sumarr[0])+sum(sumarr[1])+sum(sumarr[2]))

sum of 1st row: 6 
sum of 2nd row: 15 
sum of 3rd row: 24
sum of 1st column: 12 
sum of 2nd row: 15 
sum of 3rd row: 18
sum of given arrayis : 45


In [54]:
l11=[[1,2,3],[4,5,6],[7,8,9]]
arr11=np.array(l11)
print(arr11)
print(list(arr11))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [59]:
print(np.ones((3,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [61]:
l13=np.zeros((5,5))
print('before:\n',l13)
for i in range(len(l13)):
    l13[i,i]=i+1
print('after :\n',l13)

before:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
after :
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [76]:
l14=np.array([[1,2,3],[4,5,6],[7,8,9]])
less=[]
greater=[]
num=int(input('enter a number:'))
for j in l14:
    for i in j:
        if i>num:
            greater.append(i)
        else:
            less.append(i)
print('elements in the given array lessthan or equal to',num,'are:\n')
for i in range(len(less)):
    print(less[i],'\t')
print('elements in the given array greaterthan',num,'are:\n')
for i in range(len(greater)):
    print(greater[i],'\t')

enter a number:4
elements in the given array lessthan or equal to 4 are:

1 	
2 	
3 	
4 	
elements in the given array greaterthan 4 are:

5 	
6 	
7 	
8 	
9 	


In [77]:
l15=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l15)
s=0
print('sum of diagonal elements:')
for i in range(len(l15)):
    s+=l15[i,i]
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of diagonal elements:
15


In [83]:
l16a = np.array([1,2,3,2,3,4,3,4,5,6,7])
l16b = np.array([7,2,10,2,7,4,9,4,9,8])
common=[]
for i in l16a:
    if i in l16b:
        common.append(i)
print('common elements among given two arrays are:')
print(np.array(list(set(common))))

common elements among given two arrays are:
[2 4 7]
